plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - LICENSE

remote_theme: jekyll/minima
minima:
  skin: dark
  date_format: "%b %d, %Y"

title: Residue of my thoughts
description: Just the stuff left over from integrating my thoughts over a closed loop
tagline: Integrating my thoughts over a loop
url: https://AreamanM.github.io
